Move all of the error messaging over to activate/deactivate
All of the sys.stderr writing that happening inside the various commands
was only being used in the POSIX world as the .bat files do all of their
own error reporting.

Since these commands follow as sub-commands, the parser was grabbing
ahold of various commands and displaying its own error messages instead
of the custom ones.  This commit moves those messages out to the shell
side of things and uses exit codes to communicate back and forth.

One note, I saw some oddness in the PATH where `$HOME/anaconda/bin` was
ending up inside the PATH variable.  Since the most important thing was
to check the first value, I've written code that does just that and
ignores anything else that makes it into the path by virtue of the shell
starting on different local environments.

diff --git a/bin/activate b/bin/activate
--- a/bin/activate
+++ b/bin/activate
@@ -1,4 +1,7 @@
 #!/bin/bash
+NO_SUCH_DIRECTORY=70
+NO_SUCH_ENVIRONMENT=75
+NO_WRITE_ACCESS=80
 
 # Ensure that this script is sourced, not executed
 # Note that if the script was executed, we're running inside bash!
@@ -26,7 +29,21 @@ get_abs_filename() {
     echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
 }
 
-if "$_THIS_DIR/conda" ..checkenv "$@" 2>/dev/null; then
+# TODO Find a better way to do this that works on both bash and zsh
+case "$1" in
+"-h")
+    "$_THIS_DIR/conda" ..sourcehelp
+    return -1
+    ;;
+"--help")
+    "$_THIS_DIR/conda" ..sourcehelp
+    return -1
+    ;;
+esac
+
+"$_THIS_DIR/conda" ..checkenv "$@" 2> /dev/null
+_EXIT_CODE="$?"
+if [[ $_EXIT_CODE -eq 0 ]]; then
     _NEW_PATH=$("$_THIS_DIR/conda" ..deactivate)
     export PATH=$_NEW_PATH
     if (( $("$_THIS_DIR/conda" ..changeps1) )); then
@@ -36,8 +53,24 @@ if "$_THIS_DIR/conda" ..checkenv "$@" 2>/dev/null; then
         fi
     fi
 else
-    "$_THIS_DIR/conda" ..sourcehelp
-    return 1
+    if [[ "$#" -lt 1 ]]; then
+        >&2 echo "Error: no environment provided."
+        _EXIT_CODE=1
+    elif [[ "$#" -gt 1 ]]; then
+        >&2 echo "Error: did not expect more than one argument."
+        _EXIT_CODE=1
+    elif [[ $_EXIT_CODE -eq $NO_SUCH_DIRECTORY ]]; then
+        # TODO: Remove "bin" -- not really relevant here
+        >&2 echo "Error: no such directory: $(get_abs_filename "$@")/bin"
+    elif [[ $_EXIT_CODE -eq $NO_SUCH_ENVIRONMENT ]]; then
+        >&2 echo "Error: no such environment: $@"
+    elif [[ $_EXIT_CODE -eq $NO_WRITE_ACCESS ]]; then
+        >&2 echo "Cannot activate environment $@, do not have write access to write conda symlink"
+    else
+        "$_THIS_DIR/conda" ..sourcehelp
+        return 1
+    fi
+    return $_EXIT_CODE
 fi
 
 _NEW_PATH=$("$_THIS_DIR/conda" ..activate "$@")
diff --git a/bin/deactivate b/bin/deactivate
--- a/bin/deactivate
+++ b/bin/deactivate
@@ -20,6 +20,25 @@ else
     return 1
 fi
 _THIS_DIR=$(dirname "$_SCRIPT_LOCATION")
+_NUM_OF_ARGS="$#"
+
+# TODO Find a better way to do this that works on both bash and zsh
+case "$1" in
+"-h")
+    "$_THIS_DIR/conda" ..sourcehelp --deactivate
+    return -1
+    ;;
+"--help")
+    "$_THIS_DIR/conda" ..sourcehelp --deactivate
+    return -1
+    ;;
+esac
+
+
+if [[ $_NUM_OF_ARGS -gt 0 ]]; then
+    >&2 echo "Error: too many arguments."
+    return 1
+fi
 
 _NEW_PATH=$("$_THIS_DIR/conda" ..activateroot "$@")
 if (( $? == 0 )); then
