fix remaining Linux test failures

diff --git a/bin/activate b/bin/activate
--- a/bin/activate
+++ b/bin/activate
@@ -1,16 +1,5 @@
 #!/bin/bash
 
-# Ensure that this script is sourced, not executed
-# Also note that errors are ignored as `activate foo` doesn't generate a bad
-# value for $0 which would cause errors.
-if [[ -n $BASH_VERSION ]] && [[ "$(basename "$0" 2> /dev/null)" == "activate" ]]; then
-    >&2 echo "Error: activate must be sourced. Run 'source activate envname'
-instead of 'activate envname'.
-"
-    "$(dirname "$0")/conda" ..activate -h
-    exit 1
-fi
-
 # Determine the directory containing this script
 if [[ -n $BASH_VERSION ]]; then
     _SCRIPT_LOCATION=${BASH_SOURCE[0]}
@@ -22,6 +11,21 @@ else
 fi
 
 _THIS_DIR=$(dirname "$_SCRIPT_LOCATION")
+
+# export these so that Python subprocesses can see them (they may be shell-local)
+export PS1=$PS1
+export PROMPT=$PROMPT
+
+# Ensure that this script is sourced, not executed
+# Also note that errors are ignored as `activate foo` doesn't generate a bad
+# value for $0 which would cause errors.
+if [[ -n $BASH_VERSION ]] && [[ "$(basename "$0" 2> /dev/null)" == "activate" ]]; then
+    >&2 echo "Error: activate must be sourced. Run 'source activate envname'
+instead of 'activate envname'.
+"
+    "$_THIS_DIR/conda" ..activate -h
+    exit 1
+fi
 
 # Load common functions
 get_dirname() {
