added dash support
added all relevant dash support

addressed corner case testing for ubuntu (where the default shell is
dash as opposed to bash)

cleaned up help dialogs from activate.py to properly reflect how
c-shell vs bourne-shell sources

moved all shell detection and source vs execute detection into the top
level activate/deactivate

added/updated activate tests allowing for environment variables to be
used as opposed to passed arguments (this is important for dash/csh
support since they do not allow parameter passing when sourcing a
script)

moved awk script into separate file to avoid large duplicate copies of
identical code in activate/deactivate

added new flag to activate/deactivate (-v,--verbose) to toggle a little
more info pertaining to the activate.d/deactivate.d scripts that are
loaded into the virtual environment

diff --git a/shell/activate b/shell/activate
--- a/shell/activate
+++ b/shell/activate
@@ -1,115 +1,33 @@
+#!/bin/sh
 #
 # `source activate` initial conditional check to determine which `source activate` to actually run
 #
 # assumes that activate.* can be found on the $PATH
 #
 
-# first clause: error clause
-echo "`ps -p $$ | tr '\n' ' '` `uname -s` $SHLVL" | awk '{ \
-    num=split($0,a," ");                                \
-    if (num < 10)                                       \
-        exit 0;                                         \
-    sh="."a[8];                                         \
-    sy=a[num-1];                                        \
-    sl=a[num];                                          \
-                                                        \
-    if ((sh == ".bash")                                 ||\
-        (sh == ".-bash")                                ||\
-        (sh == "./bin/bash")                            ||\
-        (sh == ".-bin/bash")) {                         \
-        exit 1;                                         \
-    }                                                   \
-    if ((sh == ".zsh")                                  ||\
-        (sh == ".-zsh")                                 ||\
-        (sh == "./bin/zsh")                             ||\
-        (sh == ".-bin/zsh")) {                          \
-        exit 1;                                         \
-    }                                                   \
-    if ((sh == ".csh")                                  ||\
-        (sh == ".-csh" && sy == "Darwin" && sl == "1")  ||\
-        (sh == ".-sh"  && sy == "Darwin" && sl != "1")  ||\
-        (sh == ".-csh" && sy == "Linux")                ||\
-        (sh == "./bin/csh")                             ||\
-        (sh == ".-bin/csh")) {                          \
-        exit 1;                                         \
-    }                                                   \
-    if ((sh == ".tcsh")                                 ||\
-        (sh == ".-tcsh" && sy == "Darwin" && sl == "1") ||\
-        (sh == ".-csh"  && sy == "Darwin" && sl != "1") ||\
-        (sh == ".-tcsh" && sy == "Linux")               ||\
-        (sh == "./bin/tcsh")                            ||\
-        (sh == ".-bin/tcsh")) {                         \
-        exit 1;                                         \
-    }                                                   \
-    if ((sh == ".sh")                                   ||\
-        (sh == ".-sh" && sy == "Darwin" && sl == "1")   ||\
-        (sh == ".-sh" && sy == "Linux")                 ||\
-        (sh == "./bin/sh")                              ||\
-        (sh == ".-bin/sh")) {                           \
-        exit 1;                                         \
-    }                                                   \
-    exit 0;                                             \
-}'                                                      &&\
-echo '[ACTIVATE]: ERROR: Only supports sourcing from csh/tcsh and sh/bash/zsh.' &&\
-echo '[ACTIVATE]: ERROR: Your command: `'$0'`.'
+# error clause
+echo `ps -p $$ | sed 's|.*csh|THIS-IS-CSH|' | grep CSH || eval echo '$0'`                           \
+     "`ps -p $$ | tr '\n' ' '`"                                                                     \
+     "`test -x /usr/bin/lsb_release && lsb_release -si || uname -s`"                                \
+     "$SHLVL"                                                                                       \
+     "activate"                                                                                     \
+     "error-clause" | awk -f "`which .de.activate.clauses`"                                         &&\
+bash -c "echo '[ACTIVATE]: ERROR: Only supports sourcing from tcsh/csh and bash/zsh/dash.' 1>&2"
 
-# second clause: bourne shells (bash/zsh)
-echo "`ps -p $$ | tr '\n' ' '` `uname -s` $SHLVL" | awk '{ \
-    num=split($0,a," ");                                \
-    if (num < 10)                                       \
-        exit 1;                                         \
-    sh="."a[8];                                         \
-    sy=a[num-1];                                        \
-    sl=a[num];                                          \
-                                                        \
-    if ((sh == ".bash")                                 ||\
-        (sh == ".-bash")                                ||\
-        (sh == "./bin/bash")                            ||\
-        (sh == ".-bin/bash")) {                         \
-        exit 0;                                         \
-    }                                                   \
-    if ((sh == ".zsh")                                  ||\
-        (sh == ".-zsh")                                 ||\
-        (sh == "./bin/zsh")                             ||\
-        (sh == ".-bin/zsh")) {                          \
-        exit 0;                                         \
-    }                                                   \
-    if ((sh == ".sh")                                   ||\
-        (sh == ".-sh" && sy == "Darwin" && sl == "1")   ||\
-        (sh == ".-sh" && sy == "Linux")                 ||\
-        (sh == "./bin/sh")                              ||\
-        (sh == ".-bin/sh")) {                           \
-        exit 0;                                         \
-    }                                                   \
-    exit 1;                                             \
-}'                                                      &&\
-source activate.sh && return
+# bourne shell clause (bash/zsh/dash)
+echo `ps -p $$ | sed 's|.*csh|THIS-IS-CSH|' | grep CSH || eval echo '$0'`                           \
+     "`ps -p $$ | tr '\n' ' '`"                                                                     \
+     "`test -x /usr/bin/lsb_release && lsb_release -si || uname -s`"                                \
+     "$SHLVL"                                                                                       \
+     "activate"                                                                                     \
+     "bourne-shell-clause" | awk -f "`which .de.activate.clauses`"                                  &&\
+. "`which activate.sh`" && return
 
-# third clause: c-shells (tcsh/csh)
-echo "`ps -p $$ | tr '\n' ' '` `uname -s` $SHLVL" | awk '{ \
-    num=split($0,a," ");                                \
-    if (num < 10)                                       \
-        exit 1;                                         \
-    sh="."a[8];                                         \
-    sy=a[num-1];                                        \
-    sl=a[num];                                          \
-                                                        \
-    if ((sh == ".csh")                                  ||\
-        (sh == ".-csh" && sy == "Darwin" && sl == "1")  ||\
-        (sh == ".-sh"  && sy == "Darwin" && sl != "1")  ||\
-        (sh == ".-csh" && sy == "Linux")                ||\
-        (sh == "./bin/csh")                             ||\
-        (sh == ".-bin/csh")) {                          \
-        exit 0;                                         \
-    }                                                   \
-    if ((sh == ".tcsh")                                 ||\
-        (sh == ".-tcsh" && sy == "Darwin" && sl == "1") ||\
-        (sh == ".-csh"  && sy == "Darwin" && sl != "1") ||\
-        (sh == ".-tcsh" && sy == "Linux")               ||\
-        (sh == "./bin/tcsh")                            ||\
-        (sh == ".-bin/tcsh")) {                         \
-        exit 0;                                         \
-    }                                                   \
-    exit 1;                                             \
-}'                                                      &&\
+# c-shell clause (tcsh/csh)
+echo `ps -p $$ | sed 's|.*csh|THIS-IS-CSH|' | grep CSH || eval echo '$0'`                           \
+     "`ps -p $$ | tr '\n' ' '`"                                                                     \
+     "`test -x /usr/bin/lsb_release && lsb_release -si || uname -s`"                                \
+     "$SHLVL"                                                                                       \
+     "activate"                                                                                     \
+     "c-shell-clause" | awk -f "`which .de.activate.clauses`"                                       &&\
 source "`which activate.csh`" && exit $status
