Revert "Revert "Merge pull request #3175 from njalerikson/master""
This reverts commit a20c891e5be82fa425670cd8cd59ed4fa28e502d.

diff --git a/shell/deactivate b/shell/deactivate
--- a/shell/deactivate
+++ b/shell/deactivate
@@ -1,84 +1,55 @@
-#!/bin/bash
+#!/usr/bin/env bash
+###########################################################################
+# the above shebang is irrelevant since this is supposed to be sourced    #
+# it just forces bad executions of this to be in a supported shell that   #
+# can error properly                                                      #
+###########################################################################
 
-# Determine the directory containing this script
-if [[ -n $BASH_VERSION ]]; then
-    _SCRIPT_LOCATION=${BASH_SOURCE[0]}
-    _SHELL="bash"
-elif [[ -n $ZSH_VERSION ]]; then
-    _SCRIPT_LOCATION=${funcstack[1]}
-    _SHELL="zsh"
-else
-    echo "Only bash and zsh are supported"
-    return 1
-fi
-_CONDA_DIR=$(dirname "$_SCRIPT_LOCATION")
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+# #                                                                     # #
+# # DEACTIVATE                                                          # #
+# # if tree that determined which deactivate script to run              # #
+# #                                                                     # #
+# # assumes that activate*/deactivate*/whichshell*/envvar_cleanup*      # #
+# # exists on the user's $PATH                                          # #
+# #                                                                     # #
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 
-case "$(uname -s)" in
-    CYGWIN*|MINGW*|MSYS*)
-        EXT=".exe"
-        export MSYS2_ENV_CONV_EXCL=CONDA_PATH
-        ;;
-    *)
-        EXT=""
-        ;;
-esac
+###########################################################################
+# ERROR CLAUSE                                                            #
+whichshell_args.bash "deactivate" "error-clause" \
+`whichshell_ps.bash && eval 'echo $0' || echo 'csh'` | \
+awk -f "`which whichshell.awk`" || :
+# END ERROR CLAUSE                                                        #
+###########################################################################
 
-# shift over all args.  We don't accept any, so it's OK that we ignore them all here.
-while [[ $# > 0 ]]
-do
-    key="$1"
-    case $key in
-        -h|--help)
-            "$_CONDA_DIR/conda" ..deactivate $_SHELL$EXT -h
-            if [[ -n $BASH_VERSION ]] && [[ "$(basename "$0" 2> /dev/null)" == "deactivate" ]]; then
-                exit 0
-            else
-                return 0
-            fi
-            ;;
-    esac
-    shift # past argument or value
-done
+###########################################################################
+# BOURNE SHELL CLAUSE                                                     #
+# bash/zsh/dash/posh/ksh                                                  #
+whichshell_args.bash "deactivate" "bourne-shell-clause" \
+`whichshell_ps.bash && eval 'echo $0' || echo 'csh'` | \
+awk -f "`which whichshell.awk`" && . deactivate.sh || :
+# END BOURNE SHELL CLAUSE                                                 #
+###########################################################################
 
-# Ensure that this script is sourced, not executed
-# Note that if the script was executed, we're running inside bash!
-# Also note that errors are ignored as `activate foo` doesn't generate a bad
-# value for $0 which would cause errors.
-if [[ -n $BASH_VERSION ]] && [[ "$(basename "$0" 2> /dev/null)" == "deactivate" ]]; then
-    (>&2 echo "Error: deactivate must be sourced. Run 'source deactivate'
-instead of 'deactivate'.
-")
-    "$_CONDA_DIR/conda" ..deactivate $_SHELL$EXT -h
-    exit 1
-fi
+###########################################################################
+# C-SHELL CLAUSE                                                          #
+# tcsh/csh                                                                #
+whichshell_args.bash "deactivate" "c-shell-clause" \
+`whichshell_ps.bash && eval 'echo $0' || echo 'csh'` | \
+awk -f "`which whichshell.awk`" && source "`which deactivate.csh`" || :
+# END C-SHELL CLAUSE                                                      #
+###########################################################################
 
-if [[ -z "$CONDA_PATH_BACKUP" ]]; then
-    if [[ -n $BASH_VERSION ]] && [[ "$(basename "$0" 2> /dev/null)" == "deactivate" ]]; then
-        exit 0
-    else
-        return 0
-    fi
-fi
-
-if (( $? == 0 )); then
-    # Inverse of activation: run deactivate scripts prior to deactivating env
-    _CONDA_D="${CONDA_PREFIX}/etc/conda/deactivate.d"
-    if [[ -d $_CONDA_D ]]; then
-        IFS=$(echo -en "\n\b") && for f in $(find "$_CONDA_D" -iname "*.sh"); do source "$f"; done
-    fi
-
-    unset CONDA_DEFAULT_ENV
-    unset CONDA_PREFIX
-    export PATH="$CONDA_PATH_BACKUP"
-    unset CONDA_PATH_BACKUP
-    export PS1="$CONDA_PS1_BACKUP"
-    unset CONDA_PS1_BACKUP
-else
-    return $?
-fi
-
-if [[ -n $BASH_VERSION ]]; then
-    hash -r
-elif [[ -n $ZSH_VERSION ]]; then
-    rehash
-fi
+###########################################################################
+# NO-OP RETURN                                                            #
+# this will ensure that deactivate will consistently return               #
+#                                                                         #
+# since we rely heavily on the usage of return codes to detect what       #
+# scripts to run above, zero vs non-zero return codes does not            #
+# necessarily mean error                                                  #
+:
+# END NO-OP RETURN                                                        #
+###########################################################################
