fix bash on windows + make bash tests on win work

diff --git a/cmd/deactivate b/cmd/deactivate
--- a/cmd/deactivate
+++ b/cmd/deactivate
@@ -1,17 +1,5 @@
 #!/bin/bash
 
-# Ensure that this script is sourced, not executed
-# Note that if the script was executed, we're running inside bash!
-# Also note that errors are ignored as `activate foo` doesn't generate a bad
-# value for $0 which would cause errors.
-if [[ -n $BASH_VERSION ]] && [[ "$(basename "$0" 2> /dev/null)" == "deactivate" ]]; then
-    >&2 echo "Error: deactivate must be sourced. Run 'source deactivate'
-instead of 'deactivate'.
-"
-    "$(dirname $0)/conda" ..deactivate -h
-    exit 1
-fi
-
 # Determine the directory containing this script
 if [[ -n $BASH_VERSION ]]; then
     _SCRIPT_LOCATION=${BASH_SOURCE[0]}
@@ -21,7 +9,36 @@ else
     echo "Only bash and zsh are supported"
     return 1
 fi
-_THIS_DIR=$(dirname "$_SCRIPT_LOCATION")
+
+win_bash() {
+    case "$(uname -s)" in
+        CYGWIN*|MINGW*|MSYS*)
+            echo true
+            ;;
+        *)
+            echo false
+            ;;
+    esac
+}
+
+if [ $(win_bash) = true ]; then
+    _CONDA_DIR=$(dirname "$_SCRIPT_LOCATION")/../Scripts
+else
+    _CONDA_DIR=$(dirname "$_SCRIPT_LOCATION")/../bin
+fi
+
+# Ensure that this script is sourced, not executed
+# Note that if the script was executed, we're running inside bash!
+# Also note that errors are ignored as `activate foo` doesn't generate a bad
+# value for $0 which would cause errors.
+if [[ -n $BASH_VERSION ]] && [[ "$(basename "$0" 2> /dev/null)" == "deactivate" ]]; then
+    >&2 echo "Error: deactivate must be sourced. Run 'source deactivate'
+instead of 'deactivate'.
+"
+    "$_CONDA_DIR/conda" ..deactivate -h
+    exit 1
+fi
+
 # Provide a symlink-resovled script location
 _ABS_SCRIPT_LOCATION=$_SCRIPT_LOCATION
 while [ -h "$_ABS_SCRIPT_LOCATION" ]; do
@@ -48,20 +65,9 @@ get_abs_filename() {
     echo "$(get_dirname "$1")/$(basename "$1")"
 }
 
-win_bash() {
-    case "$(uname -s)" in
-        CYGWIN*|MINGW*|MSYS*)
-            echo true
-            ;;
-        *)
-            echo false
-            ;;
-    esac
-}
-
 run_scripts "deactivate"
 
-_NEW_PATH=$("$_THIS_DIR/conda" ..deactivate "$@")
+_NEW_PATH=$("$_CONDA_DIR/conda" ..deactivate "$@")
 if [ "$(win_bash)" = true ]; then
     _NEW_PATH=$(cygpath -u -p "$_NEW_PATH")
 fi
@@ -69,7 +75,7 @@ if (( $? == 0 )); then
     export PATH="$_NEW_PATH"
     unset CONDA_DEFAULT_ENV
     unset CONDA_ENV_PATH
-    _NEW_PS1=$("$_THIS_DIR/conda" ..setps1 "" "$CONDA_OLD_PS1")
+    _NEW_PS1=$("$_CONDA_DIR/conda" ..setps1 "" "$CONDA_OLD_PS1")
     PS1="$_NEW_PS1"
     unset CONDA_OLD_PS1
 else
